import Head from 'next/head'
import Image from 'next/image'
import { useEffect, useState  } from 'react';
import styles from '../styles/Home.module.css'
import axios from 'axios';
import Link from 'next/link';

export default function Home() {

  const [data, setData] = useState();

  const apiKey = "20A4ryjYJVNCptf2LDp46ahiFFe2Yyl2zPZMVOQd";
  const url = `https://api.nasa.gov/techtransfer/patent/?q=10&engine&api_key=${apiKey}`;

  const getTechTransferData = async () => {
    const res = await axios.get(url); 
    const info = await res.data; 
    console.log(info);
    setData(info);
  }

  //get all the data
  useEffect(() => { 
    getTechTransferData();
  }, []);

  return (
    <>
      <Head>
        <title>Nasa Api Test</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="relative overflow-x-auto shadow-md sm:rounded-lg">
        <h1>Collection of Nasa Images with Nasa API</h1>
        <Link href={"/polychromatic"} className="text-blue underline underline-offset-2 decoration-sky-500/30">Click to view Polychromatic Planet Viewing</Link>
        <div className="w-full text-sm text-left text-gray-500 dark:text-gray-400">
            {
              data && data.results.map((tech, index) => {
                return (
                  <div key={index}>              
                    {
                      tech && tech.map((t, ind) => {
                        if(ind === 10) {
                        return (
                          <Image src={t} alt={t} key={ind} width={200} height={200} class="px-6 py-4"/> 
                        )
                        }
                      })
                    }
                  </div>
                )
              })
            }
          </div>
      </main>
    </>
  )
}
